USE PSIO;

CREATE TABLE cars (
    registration VARCHAR(255) NOT NULL PRIMARY KEY,
    color VARCHAR(255) NOT NULL
);

CREATE TABLE logs (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    color_car1 VARCHAR(255) NOT NULL,
    color_car2 VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);